04丨Python科学计算：用NumPy快速处理数据
====

In [2]:
# 創建數組

import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1,1]=10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int64
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


In [6]:
b[1][1]

10

In [13]:
# 結構數組

import numpy as np
persontype = np.dtype({
    'names':['name', 'age', 'chinese', 'math', 'english'],
    'formats':['S32','i', 'i', 'i', 'f']})
"""
用np.dtype建立資料結構persontype，並設定：
1. 將persontype視為一個資料結構，包含各個欄位，且欄位存放的資料格式需要先做設定。
2. names即是欄位名稱，formats是在各個欄位的資料類型，names跟fornmats要成對
3. persontype.fields可以查看資料有哪些欄位
"""

peoples = np.array([("ZhangFei",32,75,100, 90),("GuanYu",24,85,96,88.5),
       ("ZhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],
    dtype=persontype)
"""
用np.array將多筆資料組成一個列表：
1. dtype設定該列表資料各筆資料依循的資料結構為persontype
2. 各組資料以tuple格式填入，persontype有name, age, chinese, math, english五個欄位。
   所以np.array([], dtype=persontype)的[]填入資料。
"""

ages = peoples[:]['age'] 
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print(np.mean(ages)) 
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

"""
1. 將列表內所有人的'age'欄位資料取出，存到ages，為numpy.ndarray的結構。
2. np.mean()求陣列內數值的平均數
ex: np.mean([12,34,5])或填入tuple也可以np.mean((12,3,4,5))
"""

28.25
77.5
93.25
93.75


In [38]:
#連續數組的創建

x1 = np.arange(1,11,2)  #(初始值, 終值(不包含), 差值)
x2 = np.linspace(1,9,5) #(初始值, 終值(包含), 元素個數), 數據是浮點數
print(np.add(x1, x2))   #相加, 相同index位置的元素相加
print(np.subtract(x1, x2)) #相減
print(np.multiply(x1,x2)) #相乘
print(np.divide(x1, x2))   #相除
print(np.power(x1, x2))    #n次方
print(np.remainder(x1, x2))#相除取餘數
print(np.mod(x1, x2))      #相同效果

[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


In [49]:
x1 = np.linspace(1,9,5)
x2 = np.linspace(1,9,4)

In [55]:
# 计数组 / 矩阵中的最大值函数 amax()，最小值函数 amin()

import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.amin(a))
print(np.amin(a,0)) 
"""
amin(a)是延着 axis=0 轴的最小值，結果為[1,2,3]
[1,2,3]
[4,5,6]
[7,8,9]
amin(a,1)是延着 axis=1 轴的最小值，結果為[1,4,7]
[1,4,7]
[2,5,8]
[3,6,9]
"""
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [2]:
# 统计最大值与最小值之差 ptp()
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.ptp(a))   # 9-1=8
print(np.ptp(a,0)) # [7,8,9] - [1,2,3] = [6,6,6]
print(np.ptp(a,1))
"""
[1,4,7]
[2,5,8]
[3,6,9]
> [3,6,9] - [1,4,7] = [2,2,2]
"""

8
[6 6 6]
[2 2 2]


In [3]:
# 统计数组的百分位数 percentile()

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

"""
同样，percentile() 代表着第 p 个百分位数，这里 p 的取值范围是 0-100，
如果 p=0，那么就是求最小值，
如果 p=50 就是求平均值，
如果 p=100 就是求最大值。
同样你也可以求得在 axis=0 和 axis=1 两个轴上的 p% 的百分位数。
ex: axis=1會轉成
[1,4,7]
[2,5,8]
[3,6,9]
"""

5.0
[4. 5. 6.]
[2. 5. 8.]


In [4]:
# 统计数组中的中位数 median()、平均数 mean()

a = np.array([[1,2,3], [4,5,6], [7,8,9]])
#求中位数
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))
"""
[1,4,7]
[2,5,8]
[3,6,9]
中間位置為[2,5,8]
"""

#求平均数
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [5]:
# 统计数组中的加权平均值 average()

a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=wts))

"""
average() 函数可以求加权平均，默认情况下每个元素的权重是相同的，np.average(a)=(1+2+3+4)/4=2.5，
你也可以指定权重数组 wts=[1,2,3,4]，np.average(a,weights=wts)=(1*1+2*2+3*3+4*4)/(1+2+3+4)=3.0。
"""

2.5
3.0


In [7]:
# 统计数组中的标准差 std()、方差 var()

a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))

"""
方差的计算是指每个数值与平均值之差的平方求和的平均值，即 mean((x - x.mean())** 2)。
标准差是方差的算术平方根。
在数学意义上，代表的是一组数据离平均值的分散程度。
所以 np.var(a)=1.25, np.std(a)=1.118033988749895。
"""

1.118033988749895
1.25


'\n方差的计算是指每个数值与平均值之差的平方求和的平均值，即 mean((x - x.mean())** 2)。\n标准差是方差的算术平方根。\n在数学意义上，代表的是一组数据离平均值的分散程度。\n所以 np.var(a)=1.25, np.std(a)=1.118033988749895。\n'

### NumPy 排序排序
算法中使用频率最高的一种，也是在数据分析工作中常用的方法，计算机专业的同学会在大学期间的算法课中学习。 
* sort 函数，sort(a, axis=-1, kind=‘quicksort’, order=None)，默认情况下使用的是快速排序
* 在 kind 里，可以指定 quicksort、mergesort、heapsort 分别表示快速排序、合并排序、堆排序。
* axis 默认是 -1，即沿着数组的最后一个轴进行排序，也可以取不同的 axis 轴，或者 axis=None 代表采用扁平化的方式作为一个向量进行排序。另外 order 字段，对于结构化的数组可以指定按照某个字段进行排序

In [8]:
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a))            # 各元素內排序，[4,3,2]變成[2,3,4]，[2,4,1]變成[1,2,4]
print(np.sort(a, axis=None)) # 降成一維排序
print(np.sort(a, axis=0))    # 對每列排序
"""
[4,3,2]
[2,4,1]
> []
"""

print(np.sort(a, axis=1))  

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


In [9]:
np.sort(a)

array([[2, 3, 4],
       [1, 2, 4]])